### ISSUE TITLE
Initial coding

### ISSUE THREAD

**Issue by gfmoore** [gfmoore/esci-precision#1]
So I've started creating the application. I'm sure you will want to make plenty of changes, but I'm just getting my head around what is going on. I've done an iteration to calculate N. I iterate until the difference between successive Ns is < 0.01.

Plenty to do yet.

**Comment by gfmoore** [comment]
Added more control and had a go at paired data.

When iterating it seems that it is possible for this to blow up? (okay diverge, though I prefer the more mathematical term ;) )

If this happens I put in an exit,but my numbers don't match yours.

Here's my code

    if (tab === 'Paired') {
      //get N,    note fmoe is the f that Prof. Cumming uses in book
      for (let fmoe = truncatedisplaypd; fmoe < 1.55; fmoe += 0.05) {
      //for (let fmoe = 0.9; fmoe < 1.55; fmoe += 0.05) {
        //iterate for N
        N = 1000;
        oldN = 0;
        while (Math.abs(N-oldN) > 0.01 ) {
          oldN = N;
          cv = Math.abs(jStat.studentt.inv( alpha/2, N - 1 ));
          N =  2 * (1 - correlationrho) * (cv/fmoe) * (cv/fmoe) ;
          if (N > oldN) {  //blowup possible
            N = oldN;
            break;
          }
        }

        Nline.push( { fmoe: parseFloat(fmoe.toFixed(2)), N: parseInt(N) } )
      }

    }

So truncatedisplaypd = 0.10
It blows up for fmoe = 0.95
alpha = 0.05
correlationrho = 0.7
targetmoe = 0.1

You mentioned 4 iterations, but I've done a check on difference between iterations.

Perhaps you can see something stupid that I've done :) 

Nline just holds an array of point objects so I can draw the curve.

BTW I'm wondering why you haven't included a select option for the Significance level, sorry your C ? It would be no problem.

**Comment by gdcumming** [comment]
Without being able to play with your latest (see comment in Issue #2) I can't compare _N_ values. I haven't mastered the fine detail of your calcs, but my calcs for _N_ 'on average' start with _N_ calculated for _z_, which doesn't require iteration.  So first try that _N_, if the MoE it gives is too long, increase _N_ by 1, etc. The _z_ and _t_ curves in ESCI for UTNS (black and red curves) show that _N_ for _t_ is at most 3 greater than _N_ for _z_. (I'm surprised it's so little different.) Maybe I did 4 iterations to be sure to be sure? Simple in-line code, maybe?

With the wider range of target MoE values that we're asking for, we'll need to check that 3 or 4 iterations still do the trick. I'd be pretty sure they would.

I didn't think to ask Bob whether he'd like _C_ to be chosen, and not always set to 95%. I'm inclined to stick with just 95% in this case, but I'll put it on my list for our next zoom.

**Comment by gfmoore** [comment]
Sorry Geoff I don't understand. Pooh bear brain.

If I'm iterating for N and trying to find it, surely I need a starting value for N in order to work out the critical value for a significance level of 0.05.

ie. the 1.96 bit. If using a student t, then I need degrees of freedom?

So I start with an assumed N of some large number and iterate till I converge (or start to diverge).

I'm thinking you didn't mean this kind of iteration. Could you write down the algorithm I need please. (I followed the calcs in UTNS but the iteration part I didn't get.

btw Now that Bob has fixed the dns for precision you should be able to see it at https://www.esci-precision.thenewstatistics.com/  

You don't need the https://www.esci-precision.thenewstatistics.com/#tab-1 or https://www.esci-precision.thenewstatistics.com/#tab-2 (though that is useful if you want to start on tab2 (I didn't know it would do that, and I'm still not quite sure why!)


regards,

Gordon Moore
gm@gordonmoore.co.uk

On 21/10/2020 06:40:28, Geoff Cumming <notifications@github.com> wrote:
Without being able to play with your latest (see comment in Issue #2 [https://github.com/gfmoore/esci-precision/issues/2]) I can't compare N values. I haven't mastered the fine detail of your calcs, but my calcs for N 'on average' start with N calculated for z, which doesn't require iteration. So first try that N, if the MoE it gives is too long, increase N by 1, etc. The z and t curves in ESCI for UTNS (black and red curves) show that N for t is at most 3 greater than N for z. (I'm surprised it's so little different.) Maybe I did 4 iterations to be sure to be sure? Simple in-line code, maybe?
With the wider range of target MoE values that we're asking for, we'll need to check that 3 or 4 iterations still do the trick. I'd be pretty sure they would.
I didn't think to ask Bob whether he'd like C to be chosen, and not always set to 95%. I'm inclined to stick with just 95% in this case, but I'll put it on my list for our next zoom.

**Comment by gfmoore** [comment]
Ohh, ignore the last email. I get it now. Using the normal doesn't require N, just start at 0.96

However, it's interesting that my method did actually converge to N. (mostly).

I'll have a go at trying it out later on or tomorrow. Too busy watching the Giro and Vuelta at the moment.


regards,

Gordon Moore
gm@gordonmoore.co.uk

On 21/10/2020 06:40:28, Geoff Cumming <notifications@github.com> wrote:
Without being able to play with your latest (see comment in Issue #2 [https://github.com/gfmoore/esci-precision/issues/2]) I can't compare N values. I haven't mastered the fine detail of your calcs, but my calcs for N 'on average' start with N calculated for z, which doesn't require iteration. So first try that N, if the MoE it gives is too long, increase N by 1, etc. The z and t curves in ESCI for UTNS (black and red curves) show that N for t is at most 3 greater than N for z. (I'm surprised it's so little different.) Maybe I did 4 iterations to be sure to be sure? Simple in-line code, maybe?
With the wider range of target MoE values that we're asking for, we'll need to check that 3 or 4 iterations still do the trick. I'd be pretty sure they would.
I didn't think to ask Bob whether he'd like C to be chosen, and not always set to 95%. I'm inclined to stick with just 95% in this case, but I'll put it on my list for our next zoom.

**Comment by gfmoore** [comment]
Actually, now that I'm programming the new calc I realise that what I did is essentially equivalent to starting with the normal z. Since I start with N = 1000, then this is basically z (at least for the first couple of decimal places.)

Anyhow on this latest release 0.0.3 I'm starting with z and doing three iterations of t. (The 4th one sometimes blows up (diverges)) at higher Target Moe 

I've tried doing the chi^2 gamma=0.99, but I must be using the function wrong (I'm using chisquared.inv(0.99, N-1) as I'm not getting what the Precision two (Old version) shows



I'm getting



On this test version, the blue line is for z, the black is for t and the red is with assurance. (Blue only appears on the "on-average" curve.

I can't be far off :)


regards,

Gordon Moore
gm@gordonmoore.co.uk

On 21/10/2020 06:40:28, Geoff Cumming <notifications@github.com> wrote:
Without being able to play with your latest (see comment in Issue #2 [https://github.com/gfmoore/esci-precision/issues/2]) I can't compare N values. I haven't mastered the fine detail of your calcs, but my calcs for N 'on average' start with N calculated for z, which doesn't require iteration. So first try that N, if the MoE it gives is too long, increase N by 1, etc. The z and t curves in ESCI for UTNS (black and red curves) show that N for t is at most 3 greater than N for z. (I'm surprised it's so little different.) Maybe I did 4 iterations to be sure to be sure? Simple in-line code, maybe?
With the wider range of target MoE values that we're asking for, we'll need to check that 3 or 4 iterations still do the trick. I'd be pretty sure they would.
I didn't think to ask Bob whether he'd like C to be chosen, and not always set to 95%. I'm inclined to stick with just 95% in this case, but I'll put it on my list for our next zoom.

**Comment by gdcumming** [comment]
0.0.3

So good to see this coming along. I'm frantically trying to figure out what I wrote, and did in Excel so many years ago. Comparing the series of N values for the Indep Groups case, I see that my two ESCI versions agree (phew!) and that they mostly agree with yours, except your values are 1 lower in a proportion of cases, also down as low as 2 for large f (target MoE). I did set Min of N = 3, tho' I guess we could think of two groups each of N=2! Not good science!

I can't diagnose why our N values are a bit different. I did figure out how I used the basic formula (13.9, p. 362 in UTNS). Here's how I found the calcs in ESCI intro (v similar in ESCI for UTNS, which allowed C to be set by user, so the formulas look a bit more complicated).
1. Sheet 'Precision two' in ESCI intro chaps 10-16
2. Review tab, unprotect sheet (no password needed)
3. View tab, click Gridlines and Headings
4. Panel 2, select upper button, see black curve
5. Click exactly on the curve, see formula pointing to $O$79:$O$107 and similar in column Q
6. Scroll down and see those two series highlighted: f values and N values for 'on average' labelled Nt
7. Look to the right and find the green column Nz which gives N as given by (13.9) using 1.96.
8. Successive pairs of columns to the right give successive iterations. The dfi is the df calculated by rounding up the column just to its left then using df = (2*N - 2). Then (13.9) is applied to get Nti, just to the right of that dfi.
9. I obviously got carried away and did 9 iterations across--9 pairs of (dfi, Nti) values.
10. Most rows settle after 2 or 3 iterations. Just a couple of cases (f = 1.7 and 2.0) oscillate for ever. (I eventually chose to display only up to 1.5 in ESCI intro.) I guess in those cases we choose the larger of the two.

Below is the 'with assurance' table, tho' I haven't looked at that in detail yet.

Have to dash off for a while.
I was wondering whether you were going to get into the vuelta as well! Is anyone crazy enough to be riding in the Tour, the Giro, and the Vuelta?!

**Comment by gdcumming** [comment]
0.0.3 Tab 2 Paired Design

I opened the paired page in the two ESCIs. Set rho = .70. Looked at the 'on average' curve, using t. Happily, the _N_ values agreed, phew. Your N values are 2 to 4 lower than mine. Again, I can't diagnose.

I went through 1-10 as above, in ESCI intro. I see that the Nz, column AB, green, uses formula 13.10, p. 363 in UTNS. Then 9 pairs of columns as for indept groups. df = N - 1. Then the Nt columns use formula 13.11.

It can take up to the fourth iteration before N stabilises, and in about 40% of cases it oscillates rather than stabilising. In such cases I choose the larger of the two oscillating values.

I haven't explored other values of rho. I'm hoping the above helps diagnose where and why our calcs differ. I can't recall what validation I did back then, but have a vague memory that I was able to check at least some values against some published values, or other software.

BTW, I'm thinking about having a curve that steps by integer values of N, rather than being straight line segments that join the N values at intervals of .05 of target MoE. I started off thinking that the steps look fussy and odd, now I'm warming to them. Let's see how our feelings about them go; it's on the list to ask Bob.

**Comment by gdcumming** [comment]
0.0.3 Tab Ind Groups Design, 'with 99% assurance' calcs

The two ESCIs agree, happily.

Your N values are higher than mine, until f is about 1.2 then yours are a bit lower.

My table of calcs is below the table for 'on average', and is labelled 'With chi-square SHORT' (yellow). Aim is to find Ntg (or Ntgamma) values. Familiar 9 pairs of columns. Start with Nz then pairs of (dfi, Nti) -- should be (dfi, Ntgi). Basic formula relies on CHIINV(.01, df) which gives the critical value of chi-square with area .01 in the right tail.

Uses the two group version of formula 13.12 on p. 371 of UTNS. I.e. replace (N - 1) with (2N - 2)

While I believe the above outlines the basics about the calc, I haven't yet figured out the fine detail of all the formulas in the table, esp. in the first few columns. I expect the complexity is added to cope with a few special cases or extreme values of some sort.

**Comment by gfmoore** [comment]
@Cycling. Sadly the Giro and Vuelta are now running concurrently, so you are in one or the other. One of you compatriots did well yesterday? (Can't remember his name). Sadly, Chris Froome (Vuelta) hasn't recovered from his crash last year, so he won't figure. It's good to see a new generation coming through with some good attacking spirit...till they become the old men.  I subscribe to the "GCN race pass", it's available worldwide, though whether your region allows live I don't know, which allows me to have the races on without adverts and is "background music" to this "changing the world" job! 😁

regards,

Gordon Moore
gm@gordonmoore.co.uk

On 22/10/2020 01:03:22, Geoff Cumming <notifications@github.com> wrote:
0.0.3
So good to see this coming along. I'm frantically trying to figure out what I wrote, and did in Excel so many years ago. Comparing the series of N values for the Indep Groups case, I see that my two ESCI versions agree (phew!) and that they mostly agree with yours, except your values are 1 lower in a proportion of cases, also down as low as 2 for large f (target MoE). I did set Min of N = 3, tho' I guess we could think of two groups each of N=2! Not good science!
I can't diagnose why our N values are a bit different. I did figure out how I used the basic formula (13.9, p. 362 in UTNS). Here's how I found the calcs in ESCI intro (v similar in ESCI for UTNS, which allowed C to be set by user, so the formulas look a bit more complicated).
* Sheet 'Precision two' in ESCI intro chaps 10-16
* Review tab, unprotect sheet (no password needed)
* View tab, click Gridlines and Headings
* Panel 2, select upper button, see black curve
* Click exactly on the curve, see formula pointing to $O$79:$O$107 and similar in column Q
* Scroll down and see those two series highlighted: f values and N values for 'on average' labelled Nt
* Look to the right and find the green column Nz which gives N as given by (13.9) using 1.96.
* Successive pairs of columns to the right give successive iterations. The dfi is the df calculated by rounding up the column just to its left then using df = (2*N - 2). Then (13.9) is applied to get Nti, just to the right of that dfi.
* I obviously got carried away and did 9 iterations across--9 pairs of (dfi, Nti) values.
* Most rows settle after 2 or 3 iterations. Just a couple of cases (f = 1.7 and 2.0) oscillate for ever. (I eventually chose to display only up to 1.5 in ESCI intro.) I guess in those cases we choose the larger of the two.
Below is the 'with assurance' table, tho' I haven't looked at that in detail yet.
Have to dash off for a while.
I was wondering whether you were going to get into the vuelta as well! Is anyone crazy enough to be riding in the Tour, the Giro, and the Vuelta?!

**Comment by gfmoore** [comment]
So I've been analysing your calcs and they are driving me nuts. It's really hard in Excel to see the details of a calc. Laughing.

So one thing is that there is a difference between TINV and T.INV (and the jStat equivalent), happily I was actually using alpha/2 so that was okay. 

But I am not happy, or sure I understand the way you are moving between N and degrees of freedom and the rounding or forcing to highest integer value that is going on.

I guess this is because I don't understand the process. 

One thing that does concern me the most is:

dfn =   MAX(      MIN(  2 * ROUNDUP( Nt(n-1) , 0 ) - 2,    df(n-1) + 2),     df(n-1) -2)

the n is the current iteration and n-1 is the previous one. 

Comparing calcs using N and df is suspicious. I know you will have good reasons for this. laughing again.

I decided to iterate using the exact values. Amazingly, jStat does allow the use of non integer values for degrees of freedom. I' assume it does some kind of interpolation?

I got the same values as you did without all the manipulations!

For the record my code does the following:

Choose alpha = 0.05
Let's choose f = 0.25

calculate the inverse normal to get the critical value cv for alpha/2  (this is norm.inv in Excel or jStat.normal.inv(alpha/2, 0, 1) in JavaScript) the absolute value of this is of course 1.9623366606025012  

Now calculate N = 2 * (cv/f)^2    (There is no ^2 in JS o 2 * (cv/f) * (cv/f). This gives 122.9266822622121
If N < 3 make N = 3.

Now I use the Student t inverse function.
cv = jStat.studentt.inv( alpha/2, 2 * N - 2)    this N is a real number (floating point) from above.
N = 2 * (cv/f)^2   again giving a real number (floating point)

I then iterated another 8 times like you did in the spreadsheet, except I haven't manipulated N

I then use the JS equivalent of ROUNDUP (Math.ceil) on the last entry (at the moment - I think you take the higher one.

Anyway it came out the same. Perhaps it won't after further testing.

Well, I suddenly ran out of time today, so I'll update what I have, but I have only played with independent groups and average. Too busy watching an amazing Giro stage. :)

**Comment by gfmoore** [comment]
Here's an interesting observation/question. (I haven't gone to bed as I'm now looking at your assurance calcs and wishing I hadn't started....) :()

Just like TINV and T.INV are not the same I have now discovered that CHIINV and CHI.INV are not the same, CHINV and CHI.INV.RT are the same(ish). These give the right tail. However jStat only has chisq.inv which gives the left tail. How can I get the CHI.INV.RT from the CHI.INV? 

How on earth did you come up with your formulae?!!!!   laughing and crying, not sure which. ;)

**Comment by gdcumming** [comment]
0.0.4

I send you MUCH empathy in trying to figure out the calcs, also many apologies. All I can say is that in 1997, when I had to choose what setting I would use to develop stats software, by myself and still with a day job, I looked at several possibilities and took advice, and Excel was clearly the best choice. And it has been ok, but is long superseded. Which is why what you are doing in javascript, etc, and Bob is doing in R, are so vital.

The Excel formulas, esp when going back to them after so many years, are definitely mysterious. One reason is that, very often, the core formula that does the real work is surrounded by lots of IFs and other peripheral stuff, typically added like successive pairs of brackets at the start and end, during debugging and refinement, to cope with extreme cases, or to allow switching on and off of various features for display.

When I calc the RH tail of 2.5% for a normal, I get 1.959963985  not the slightly higher value you state above. I used NORMSINV(.975), which is one of Excel's formulas that is still included, for compatibility with old programs. But I believe that value is correct.

Where did I get the formulas for N? I was following some then-recent papers, esp by Ken Kelly, who has always been at the forefront of precision-for-planning. He more often uses the term AIPE, accuracy in parameter estimation. But the formulas and descriptions, such as they are, in pp 361-363 and 371, of UTNS, are I believe correct and the basics of what we need.

I'll wait before trying myself to do further work on deciphering and interpreting my formulas with so many 'roundup' steps. But I'll certainly try that, if you think it could help.

Bottom line--if you can calc values that agree with ESCI in all cases, then we are done. (I'm about to email Bob with my list of qq, one of which is about any suggestions for some way to validate the N values given in ESCI.)

You talk about N vs df, and swapping back and forth. I suspect I didn't keep the two neatly separated in ESCI, sorry. To some extent they play different roles. For example, when transferring from the formulas for single groups to the equivalents for two independent groups, the df changes from (N - 1) to 2(N - 1), but the sqrt(1/N) becomes sqrt(2/N) -- when N is size of each of the two groups.

CHIINV(0.01,10) = 23.20925116 -- legacy function (for legacy folks, like me...)
CHISQ.INV(0.99,10) = 23.20925116
CHISQ.INV.RT(0.01,10) = 23.20925116

---
I haven't been following either big cycle race, but did note in today's newspaper that an Aussie, whom I'd never heard of, won a stage in the Giro, after having just been beaten into second place the previous day. Not a bad effort to be right at the front, two days in a row.

**Comment by gfmoore** [comment]
>> When I calc the RH tail of 2.5% for a normal, I get 1.959963985 not the slightly higher value you state above. I used

oops. I nearly had a heart attack. Just checked and I get 1.9599639845400547. No idea where the above value came from (perhaps after an iteration, it was a bit late!!!)

**Comment by gfmoore** [comment]
Thanks for the chisq. Feel very dense not thinking about using 0.99 doh.

**Comment by gfmoore** [comment]
>> All I can say is that in 1997, when I had to choose what setting I would use to develop stats software, by myself and still with a day job, I looked at several possibilities and took advice, and Excel was clearly the best choice. 

I'm amazed that you did so much. I've actually learn quite a lot just trying to decipher how you did things, and when I see how much you did, I wonder you even managed your day job :)

I'm going to close this issue. We can concentrate on opening issues for particular problems, development now I think, otherwise I am going to confuse us all :)
