### ISSUE TITLE
Display of N on MoE distribution

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-precision#10]
0.1.12

I like the way the vertical line that's the prob density axis moves and changes height for different targ MoE values, different curves, etc.

For the display of N on the curve itself, it's probably impossible to position it in a way that's ideal for every possible case, given the vast variety of widths and heights that the MoE distribution takes.

On the whole, the current way N is shown on that curve isn't bad, and it's good that it shifts, and that's it's always on--unlike in ESCI intro. But I suggest two changes:

1. Let's have the number itself in brown, same as the MoE distribution curve, and bold. So it's more closely perceptually linked to that curve. 

2. Is it possible to have it overall closer to the curve? At the moment it's often left out to the left of the curve, and may be seen as a value on the prob density axis. I know it probably has to shift relative to the curve. The way it changes height seems fine. But better I think would be closer to the curve, where possible a little to the left of the curve itself, or overlaying the left side of the curve.

**Comment by gfmoore** [comment]
Done?

**Comment by gdcumming** [comment]
0.1.17
Positioning of N on curve is great. Bold is good.
I keep changing my mind as to whether the N on the curve should switch off with the other N values. Also, is N on curve a bit large? But I'm going to say it's all great. And close... And if, just maybe, Bob feels strongly, maybe we'll come back to you.
