### ISSUE TITLE
Grey N on cursor

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-precision#11]
0.1.17

I'm back to working on Chapter 10, for which pfp is critical. So I'm noticing at least one thing I'd overlooked.

Both tabs: Could we have grey N at the cursor when assurance is selected. Should stay visible when 'Display all N values' is clicked off. Bold, and same size as red N at cursor.

**Comment by gfmoore** [comment]
Done, but positioning is very hard for different scenarios. I've done the best I can, but perhaps there is a different approach? The same with the MoE curve N.

**Comment by gdcumming** [comment]
0.1.19

Thanks. N on MoE curve works well. The grey N at cursor is good, but could be a bit more visible. Bold? Or maybe it is already. Or one small click darker grey?

I don't know how fine your control of positioning can be, but the grey N at cursor feels to me as if it could go a whisker right and a whisker higher. No big deal if not possible--I know I'm getting down to tiny detail.

**Comment by gfmoore** [comment]
It was bold, but adjusted. Btw I do spend a lot of time positioning in such a way as to balance all the conflicting demands.

**Comment by gdcumming** [comment]
0.1.21
I never doubted that for a moment! I've done enough of this sort of stuff over the years to know that vast fiddling and experimenting is required to get things working and looking so well.
Latest version is v good, thanks. Closing...
