### ISSUE TITLE
Gridlines?

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-precision#12]
0.1.17

I see I invented a new nickname for a controllable vertical line in a graph: the "curso". Sure to catch on.

I've stared so long at the displays that I fancy I see pale grey H and V gridlines. But I don't think they are there. Could we try with real gridlines, very pale or pale but visible? I'm thinking perhaps every 0.1 along H axis, and where there are numerals on the V axis. That would really help the eyeballing needed for the exercises I'm writing about in Ch 10. Esp. the vertical lines. Thanks.

**Comment by gfmoore** [comment]
No, there were no gridlines in keeping with all previous programs! However, I've added a Gridlines checkbox so if you want them you can have them. 😄

**Comment by gdcumming** [comment]
0.1.19

They are great. And this is the only component of esci web that needs them.

I'm tempted to say that we can just always have them on, but now you've built the checkbox option, let's leave folks the option to have them on or off. 

I suggest, for both tabs:

Default is always gridlines on.

Revise top line in Panel 3 (Ind gps tab) or 4 (Paired tab):

3 <or 4> Display features
... with tip: "Turn features on or off"

Tips for the two features and checkboxes are fine.

**Comment by gfmoore** [comment]
Done

**Comment by gdcumming** [comment]
0.1.21
Great, thanks. (Gridlines are so good...) One tiny tweak please: text in line 1 of that panel: "Display features" rather than "Display values" -- to fit with what the two checkboxes offer.
Closing...

**Comment by gdcumming** [comment]
PS
I think we are on the verge of being ready to release all of esci web as a whole. Fabulous! But we'd better hold off until I can have a word with Bob, I hope Mon or Tues next week. I know we've been holding our breath over the US election, and I'm sure it's even more stressful and scary where he is. Looking forward to being able to breathe out soon. Geoff

**Comment by gfmoore** [comment]
>> text in line 1 of that panel: "Display features" 

Done 😃
