### ISSUE TITLE
Default states

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-precision#4]
0.0.6

On opening, all seems fine, except that target MoE value in Panel 1 of both tabs is 0.25 instead of 0.40. Swapping between tabs doesn't update that value, but changing the slider does.

Otherwise the look and feel and performance of all the panels, at both tabs, seems fine.

Many aspects of how the curves look and behave also seem fine.

I hope to reach Bob on zoom tomorrow and reach decisions about my list of qq. More soon.

**Comment by gfmoore** [comment]
Sorry, missed that one.

I also note that the displays are only to 2dp. I'll await the result of your zoom conversation as to the increment size for the Target Moe, currently at 0.005.

**Comment by gdcumming** [comment]
0.1.0
Thanks, closing.
Still hoping to reach Bob today, tho' I have a time clash. May have to be tomorrow.
