### ISSUE TITLE
Paired Design, ceiling on N

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-precision#5]
0.0.6

Paired tab. Set 'truncate' to 0.05, the minimum. Then for rho < .69 (on average) and rho < .71 (with assurance) it seems that N = 999 is set as a ceiling. For very low rho, the curve shows a small horizontal black or red line at N = 999.

At Two Ind Groups tab, values of N > 1,000 are reported, so the ceiling seems to apply only for Paired tab.

**Comment by gfmoore** [comment]
Indeed I did. The reason for this was to stop the oscillation of values at higher levels of target MoE, I wanted to just take the minimum values and of course to check for a minimum you need to set a high value to compare against. I used 999. Obviously too small, so I've upped this to 999999. I cannot imagine a situation where someone might need a sample of one million, but if this could occur, let me know!!!

**Comment by gdcumming** [comment]
0.1.0
I see. I haven't tackled your formulas (thanks) yet. Max N is now 3256, for rho=0, targ MoE=0.05, assurance. So your chosen max is plenty big! Closing...
