### ISSUE TITLE
Slider interactions, target MoE and truncation

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-precision#7]
0.1.0

Target MoE setting is yoked between the two tabs, but truncation setting is not. That can give slightly odd situations, e.g. with the cursor (at target MoE) fully to the left of the truncation point (after swapping tabs) so with no N value or MoE curve displayed at the cursor. Instantly corrected if any change made. Maybe leave that as is, at least for the moment. It's OK, or at worst a very minor problem.

Overall the interaction of the two sliders works better than in ESCI :-)

But there's one inconsistency: at the Two ind groups tab, but not Paired Design tab:
If move truncation slider by clicking and dragging the thumbnail (? the circle on the slider), not by using the nudge buttons, then that slider 'grabs' the cursor and target MoE is reset and moves with the truncation slider.

**Comment by gfmoore** [comment]
>> Target MoE setting is yoked between the two tabs, but truncation setting is not. That can give slightly odd situations, e.g. with the cursor (at target MoE) fully to the left of the truncation point (after swapping tabs) so with no N value or MoE curve displayed at the cursor. Instantly corrected if any change made. Maybe leave that as is, at least for the moment. It's OK, or at worst a very minor problem.

Fixed, I think

>> If move truncation slider by clicking and dragging the thumbnail (? the circle on the slider), not by using the nudge buttons, then that slider 'grabs' the cursor and target MoE is reset and moves with the truncation slider.

I've now made Independent groups the same as Paired design.

**Comment by gdcumming** [comment]
0.1.3
The way trunc and MoE sliders work, and linking b'n tabs seems to me fine. Thanks. Closing

**Comment by gfmoore** [comment]
😃 You must have just got up, I'm just off to bed. Hope the rest of it works as you want. Its been a tough one for me. It must have taken you ages to get Excel to do it, amazing.

⁣Regards,

Gordon Moore
gm@gordonmoore.co.uk​
