### ISSUE TITLE
Tips

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-precision#8]
0.1.9

Line 2: precision for planning: "Find the smallest _N_ that will give a 95% CI with MoE no more than chosen target MoE, either on average, or with 99% assurance"

Tab 1: "Two Independent Groups Design, each group of size _N_"

Tab 2: "Paired Design", with group of size _N_"

1 Target MoE of  95% CI: "Use large slider below figure to choose a value for target MoE"
[target MoE value]: "Value of target MoE, marked by position of cursor"
...set by slider below figure: "Use large slider below figure to choose a value for target MoE"

2 _N_ curves: "Curves show the relation between _N_ and target MoE"
(o) _N_ curve for target MoE, **on average**: "Black curve shows how _N_ varies with target MoE on average"
(o) _N_ curve for target MoE, **with 99% assurance**: "Red curve shows how _N_ varies with target MoE with 99% assurance (grey curve: on average)"

3 Display values: "Turn on or off the display of _N_ values at each point on displayed curve(s)"
Display all _N_ values [..]: "Turn on or off the display of _N_ values at each point on displayed curve(s)"

4 Truncate display at target MoE value of: "Use slider to choose where to truncate the left end of curve(s)"
[slider]: "Select a value within 0.05 and 0.30"
[value]: "Left-truncate curve(s) at this value"

**Comment by gfmoore** [comment]
I think we need something for correlation in paired?

**Comment by gdcumming** [comment]
0.1.12

Sorry for the rho lacuna!

The long statement "Find the smallest..." I'd intended as a tip on 'precision for planning', but I prefer it the way you have done it! stet

Tweaks please:

Ind Groups tab:

Panel 2: All three tips, italic _N_

Trunc slider: "... between 0.05 and 0.30" is better than "within". My error.

Paired Design tab: Remove double quote. My error, sorry.

2 Population correlation: "Use slider to set population correlation ρ" 
Correlation ρ: "Use slider to set population correlation ρ"
Slider: "Set ρ between .00 and .99"
[..]: "ρ"

Panels 3, 4, 5: Same as for Panels 2, 3, 4 of Ind Groups tab.

**Comment by gfmoore** [comment]
Done.

**Comment by gdcumming** [comment]
0.1.17
Thanks, closing...
