### ISSUE TITLE
Figure legend

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-precision#9]
0.1.12

I guess, being a bit picky, the legend for the black and grey curves should be: 
_N_, for average MoE ≤ target MoE

... given that I guess there isn't room (esp for smaller viewports) for the clearer statement:
_N_, for average MoE no more than target MoE

**Comment by gdcumming** [comment]
0.1.12

Playing more with viewport size I notice that moving the RH edge in leads to excellent adjustment of the x axis and the curves, but that the figure legend is truncated.

If that's tricky to fix, I'd be happy to satisfice with what we have. A partial fix could be simply to shift the whole legend a bit to the left, given that the top right of the display area is blank in all situations. 

If some adjustment works, would there be convenient room for the more complete statement above (... no more than...) rather than ≤?

**Comment by gfmoore** [comment]
Okay, so I've added code that splits the average legend, but for very small widths there's not really a lot I can do!

**Comment by gdcumming** [comment]
0.1.17
Great, closing...

I think we're just waiting for my being able to discuss a few things with Bob. Otherwise done! Big high five!
